version: '3.8'

services:
  gunicorn:
    build: 
      context: ./notifications
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  redis:
    image: redis:alpine
  celery:
    build: ./notifications
    command: celery -A config worker -l info
    volumes: 
      - ./notifications/:/app/
    env_file:
      - ./.env
    depends_on:
      - redis
  celery-beat:
    build: ./notifications
    command: celery -A config beat -l info
    volumes: 
      - ./notifications/:/app/
    env_file:
      - ./.env
    depends_on:
      - redis
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data: 
  static_volume:
  media_volume: