# Generated by Django 3.2.18 on 2023-08-30 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=45, verbose_name='Category name')),
                ('color', models.CharField(max_length=15, verbose_name='Color')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification category',
                'verbose_name_plural': 'Notification categories',
            },
        ),
    ]
