# Generated by Django 3.2.18 on 2023-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='Slug'),
        ),
    ]
