# Generated by Django 3.2.18 on 2023-08-30 13:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('notification_type', models.CharField(max_length=30, verbose_name='Notification')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Notification task id',
                'verbose_name_plural': 'Notification task id`s',
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True, null=True, verbose_name='Time stamp')),
                ('done', models.IntegerField(choices=[(0, 'Not Complited'), (1, 'Complited'), (2, 'Revoked')], default=0, verbose_name='Status')),
                ('notification_celery_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationid', verbose_name='Celery id')),
            ],
            options={
                'verbose_name': 'Notification status',
                'verbose_name_plural': 'Notification statuses',
            },
        ),
        migrations.CreateModel(
            name='NotificationSingle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=350, verbose_name='Text')),
                ('notification_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('notification_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('notification_category', models.ForeignKey(default='study', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_categories.notificationcategory', verbose_name='Category')),
                ('notification_status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationstatus', verbose_name='Status')),
                ('notification_type_single', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_single', to='notifications.notificationbase', verbose_name='Notification type')),
            ],
            options={
                'verbose_name': 'Notification single',
                'verbose_name_plural': 'Notifications single',
            },
        ),
        migrations.CreateModel(
            name='NotificationPeriodicity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('text', models.TextField(max_length=350, verbose_name='Text')),
                ('notification_periodicity_num', models.IntegerField(default=0, verbose_name='Number of repetitions')),
                ('notification_periodic_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None, verbose_name='Dates')),
                ('notification_category', models.ForeignKey(default='study', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification_categories.notificationcategory', verbose_name='Category')),
                ('notification_status', models.ManyToManyField(related_name='notification_periodic_statuses', to='notifications.NotificationStatus', verbose_name='Status')),
                ('notification_type_periodicity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_periodic', to='notifications.notificationbase', verbose_name='Notification type')),
            ],
            options={
                'verbose_name': 'Notification periodic',
                'verbose_name_plural': 'Notifications periodic',
            },
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='task_id',
            field=models.ManyToManyField(blank=True, null=True, to='notifications.NotificationId', verbose_name='Tasks'),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
