# Generated by Django 3.2.18 on 2023-09-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationbase',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notificationbase',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='notificationperiodicity',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='notificationperiodicity',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='notificationperiodicity',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notificationperiodicity',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='notificationsingle',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='notificationsingle',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='notificationsingle',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notificationsingle',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
    ]
