# Generated by Django 3.2.18 on 2023-09-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20230903_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationbase',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='notificationbase',
            name='meta_copyright',
        ),
        migrations.RemoveField(
            model_name='notificationbase',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='notificationbase',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='notificationperiodicity',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='notificationperiodicity',
            name='meta_copyright',
        ),
        migrations.RemoveField(
            model_name='notificationperiodicity',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='notificationperiodicity',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='notificationsingle',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='notificationsingle',
            name='meta_copyright',
        ),
        migrations.RemoveField(
            model_name='notificationsingle',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='notificationsingle',
            name='meta_keywords',
        ),
    ]
