# Generated by Django 3.2.18 on 2023-08-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tz',
            field=models.CharField(choices=[('Atlantic/Reykjavik', 'UTC 00:00 ( for example Reykjavik, Lisbon '), ('Europe/London', 'UTC +01:00 ( for example, London, Dublin )'), ('Europe/Kaliningrad', 'UTC +02:00 ( for example, Kaliningrad, Berlin, Paris, Warsaw, Zagreb )'), ('Europe/Moscow', 'UTC +03:00 ( for example, Moscow, Riga, Saint Petersburg, Minsk, Volgograd, Kirov )'), ('Europe/Samara', 'UTC +04:00 ( for example, Baku, Tbilisi, Yerevan, Samara, Ulyanovsk )'), ('Asia/Kabul', 'UTC +04:30 ( for example, Kabul )'), ('Asia/Yekaterinburg', 'UTC +05:00 ( for example, Yekaterinburg, Tashkent )'), ('Asia/Almaty', 'UTC +06:00 ( for example, Almaty, Omsk, Bishkek )'), ('Asia/Krasnoyarsk', 'UTC +07:00 ( for example, Novosibirsk, Krasnoyarsk, Novokuznetsk, Bangkok, Hanoi, Jakarta )'), ('Asia/Irkutsk', 'UTC +08:00 ( for example, Irkutsk, Beijing, Hong Kong, Singapore )'), ('Asia/Yakutsk', 'UTC +09:00 ( for example, Yakutsk, Tokyo, Osaka )'), ('Asia/Vladivostok', 'UTC +10:00 ( for example, Vladivostok, Canberra, Melbourne, Sydney )'), ('Asia/Magadan', 'UTC +11:00 ( for example, Magadan, Solomon Islands, New Caledonia )'), ('Asia/Kamchatka', 'UTC +12:00 ( for example, Fiji Islands, Kamchatka, Marshall Islands )'), ('EST', 'UTC -05:00  (Eastern US and Canada)'), ('US/Central', 'UTC -06:00 ( for example, Central America )'), ('US/Arizona', 'UTC -07:00 ( for example, Arizona )'), ('US/Alaska', 'UTC -08:00 ( for example, Alaska )'), ('US/Hawaii', 'UTC -10:00 ( for example, Hawaii )')], default='Atlantic/Reykjavik', help_text='If you don`t know your timezone, please google it! This field is important for sending notifications correctly.', max_length=100, verbose_name='Timezone'),
        ),
    ]
